name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # Change this to your default branch if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud functions deploy api \
            --gen2 \
            --runtime=python312 \
            --region us-central1 \
            --source=. \
            --entry-point=hello_http \
            --trigger-http \
            --allow-unauthenticated \
            --service-account=cloud-build@${{ secrets.GCP_PROJECT }}.iam.gserviceaccount.com